"""'created_time'

Revision ID: 2adf75c346d6
Revises: 4c8bbd4968fd
Create Date: 2022-04-12 18:51:57.082049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2adf75c346d6'
down_revision = '4c8bbd4968fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admission', sa.Column('created_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admission', 'created_time')
    # ### end Alembic commands ###
