"""status add

Revision ID: c492e828cd3b
Revises: 7c7ccadb561c
Create Date: 2022-04-12 21:29:30.903956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c492e828cd3b'
down_revision = '7c7ccadb561c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admission', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admission', 'status')
    # ### end Alembic commands ###
